// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddSite: typeof import('./components/package/AddSite.vue')['default']
    Autocomplete: typeof import('./components/Autocomplete.vue')['default']
    Bookmarks: typeof import('./components/package/Bookmarks.vue')['default']
    Calendar: typeof import('./components/package/Calendar.vue')['default']
    Clock: typeof import('./components/package/Clock.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    History: typeof import('./components/package/History.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ModalNew: typeof import('./components/ModalNew.vue')['default']
    Note: typeof import('./components/Note.vue')['default']
    PopoverNew: typeof import('./components/PopoverNew.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    SearchLogo: typeof import('./components/SearchLogo.vue')['default']
    Site: typeof import('./components/Site.vue')['default']
    User: typeof import('./components/User.vue')['default']
  }
}
